import type { EventQuotaRule } from "@/lib/types";

export type QuotaRule = EventQuotaRule & {
  eventId: string;
  mainParticipants: number;
};

export const CODEX_QUOTAS: QuotaRule[] = [
  // General / Institutional
  { eventId: "cricket", mainParticipants: 9, substitutes: 2 },
  { eventId: "volleyball", mainParticipants: 6, substitutes: 3 },
  { eventId: "tug-of-war", mainParticipants: 8, substitutes: 4, maxTeamWeightKg: 600, notes: "Total team weight must not exceed 600 kg." },
  { eventId: "commentary", mainParticipants: 2 },
  { eventId: "penalty-shootout", mainParticipants: 4 },
  { eventId: "football", mainParticipants: 7, substitutes: 3 },
  { eventId: "throwball", mainParticipants: 7, substitutes: 3 },
  { eventId: "uriyadi-general", mainParticipants: 2 },
  { eventId: "chess-general", mainParticipants: 1 },

  // Majestir — Super Senior
  { divisionId: "majestir", eventId: "race-100m", mainParticipants: 2 },
  { divisionId: "majestir", eventId: "relay-4x100m", mainParticipants: 4, groups: 1 },
  { divisionId: "majestir", eventId: "long-jump", mainParticipants: 2 },
  { divisionId: "majestir", eventId: "high-jump", mainParticipants: 2 },
  { divisionId: "majestir", eventId: "arm-wrestling", mainParticipants: 2 },
  { divisionId: "majestir", eventId: "push-up", mainParticipants: 2 },
  { divisionId: "majestir", eventId: "pull-up", mainParticipants: 2 },
  { divisionId: "majestir", eventId: "shot-put", mainParticipants: 2 },
  { divisionId: "majestir", eventId: "javelin-throw", mainParticipants: 2 },
  { divisionId: "majestir", eventId: "discus-throw", mainParticipants: 2 },
  { divisionId: "majestir", eventId: "juggling", mainParticipants: 2 },
  { divisionId: "majestir", eventId: "badminton-singles", mainParticipants: 1 },
  { divisionId: "majestir", eventId: "archery", mainParticipants: 1 },
  { divisionId: "majestir", eventId: "basket-throw", mainParticipants: 2 },
  { divisionId: "majestir", eventId: "chess", mainParticipants: 1 },
  { divisionId: "majestir", eventId: "swimming", mainParticipants: 1 },
  { divisionId: "majestir", eventId: "shot-on-target", mainParticipants: 2 },

  // Aliya — Senior
  { divisionId: "aliya", eventId: "race-100m", mainParticipants: 3 },
  { divisionId: "aliya", eventId: "relay-4x200m", mainParticipants: 4, groups: 1 },
  { divisionId: "aliya", eventId: "long-jump", mainParticipants: 3 },
  { divisionId: "aliya", eventId: "high-jump", mainParticipants: 3 },
  { divisionId: "aliya", eventId: "arm-wrestling", mainParticipants: 2 },
  { divisionId: "aliya", eventId: "push-up", mainParticipants: 2 },
  { divisionId: "aliya", eventId: "pull-up", mainParticipants: 2 },
  { divisionId: "aliya", eventId: "shot-put", mainParticipants: 3 },
  { divisionId: "aliya", eventId: "javelin-throw", mainParticipants: 3 },
  { divisionId: "aliya", eventId: "discus-throw", mainParticipants: 3 },
  { divisionId: "aliya", eventId: "freestyle", mainParticipants: 1 },
  { divisionId: "aliya", eventId: "badminton-singles", mainParticipants: 1 },
  { divisionId: "aliya", eventId: "basket-throw", mainParticipants: 3 },
  { divisionId: "aliya", eventId: "dart-board", mainParticipants: 2 },
  { divisionId: "aliya", eventId: "chess", mainParticipants: 1 },
  { divisionId: "aliya", eventId: "swimming", mainParticipants: 1 },
  { divisionId: "aliya", eventId: "corner-kick-goal", mainParticipants: 3 },

  // Thamheediyya — Pre Senior
  { divisionId: "thamheediyya", eventId: "race-100m", mainParticipants: 4 },
  { divisionId: "thamheediyya", eventId: "relay-4x100m", mainParticipants: 4, groups: 2 },
  { divisionId: "thamheediyya", eventId: "long-jump", mainParticipants: 3 },
  { divisionId: "thamheediyya", eventId: "high-jump", mainParticipants: 3 },
  { divisionId: "thamheediyya", eventId: "arm-wrestling", mainParticipants: 2 },
  { divisionId: "thamheediyya", eventId: "push-up", mainParticipants: 4 },
  { divisionId: "thamheediyya", eventId: "pull-up", mainParticipants: 4 },
  { divisionId: "thamheediyya", eventId: "juggling", mainParticipants: 2 },
  { divisionId: "thamheediyya", eventId: "bowling", mainParticipants: 2 },
  { divisionId: "thamheediyya", eventId: "badminton-doubles", mainParticipants: 2 },
  { divisionId: "thamheediyya", eventId: "slow-cycle", mainParticipants: 1 },
  { divisionId: "thamheediyya", eventId: "crossbar-kick", mainParticipants: 3 },
  { divisionId: "thamheediyya", eventId: "uriyadi", mainParticipants: 3 },
  { divisionId: "thamheediyya", eventId: "dart-board", mainParticipants: 3 },
  { divisionId: "thamheediyya", eventId: "chess", mainParticipants: 1 },
  { divisionId: "thamheediyya", eventId: "swimming", mainParticipants: 1 },
  { divisionId: "thamheediyya", eventId: "discus-throw", mainParticipants: 3 },

  // Thaniya — Junior
  { divisionId: "thaniya", eventId: "race-100m", mainParticipants: 2 },
  { divisionId: "thaniya", eventId: "relay-4x100m", mainParticipants: 4 },
  { divisionId: "thaniya", eventId: "long-jump", mainParticipants: 3 },
  { divisionId: "thaniya", eventId: "high-jump", mainParticipants: 3 },
  { divisionId: "thaniya", eventId: "sack-race", mainParticipants: 2 },
  { divisionId: "thaniya", eventId: "slow-cycle", mainParticipants: 1 },
  { divisionId: "thaniya", eventId: "skipping", mainParticipants: 3 },
  { divisionId: "thaniya", eventId: "bowling", mainParticipants: 2 },
  { divisionId: "thaniya", eventId: "badminton-singles", mainParticipants: 1 },
  { divisionId: "thaniya", eventId: "water-filling-group", mainParticipants: 2 },
  { divisionId: "thaniya", eventId: "single-leg-hula-hoop", mainParticipants: 1 },
  { divisionId: "thaniya", eventId: "push-up", mainParticipants: 3 },
  { divisionId: "thaniya", eventId: "bottle-hit", mainParticipants: 2 },
  { divisionId: "thaniya", eventId: "dart-board", mainParticipants: 3 },
  { divisionId: "thaniya", eventId: "swimming", mainParticipants: 1 },

  // Bidaya — Sub Junior
  { divisionId: "bidaya", eventId: "race-100m", mainParticipants: 4 },
  { divisionId: "bidaya", eventId: "relay-4x50m", mainParticipants: 4, groups: 2 },
  { divisionId: "bidaya", eventId: "water-filling", mainParticipants: 3 },
  { divisionId: "bidaya", eventId: "hopscotch", mainParticipants: 3 },
  { divisionId: "bidaya", eventId: "balloon-pyramid", mainParticipants: 3 },
  { divisionId: "bidaya", eventId: "biscuit-eating", mainParticipants: 4 },
  { divisionId: "bidaya", eventId: "balloon-pop", mainParticipants: 3 },
  { divisionId: "bidaya", eventId: "candle-race", mainParticipants: 3 },
  { divisionId: "bidaya", eventId: "musical-chair", mainParticipants: 4 },
  { divisionId: "bidaya", eventId: "skipping", mainParticipants: 3 },
  { divisionId: "bidaya", eventId: "race-walking-100m", mainParticipants: 3 },
  { divisionId: "bidaya", eventId: "long-jump", mainParticipants: 3 },
  { divisionId: "bidaya", eventId: "three-legged-race", mainParticipants: 2 },
  { divisionId: "bidaya", eventId: "kho-kho", mainParticipants: 8 },
];
